---
- name: Installing/Uninstalling Package and Choosing Service State in selected Hosts
  hosts: webservers
  remote_user: root
  tasks:

  - name: setting default value
      set_fact: change_state=no
    when: change_state is undefined

  - name: Installing "{{package_name}}"
    yum: 
      name: "{{package_name}}"
      state: "{{package_state}}"
      enablerepo: "{{repo_name}}"
  - block:
      - name: changing "{{service_name}}" service state to "{{service_state}}"
      service: 
        name: "{{service_name}}"
        state: "{{service_state}}"
      when: change_state == "yes"

#    - name: Starting httpd service to start
#      service:
#        name: httpd
#        state: started
#      when: 

     - name:
       lvol:
         name:
         vg:
       when: ansible
