---
- name: Installing/Uninstalling Package and Choosing Service State in selected Hosts
  hosts: webservers
  remote_user: root
  tasks:

  - name: Installing "{{package_name}}"
    yum: 
      name: httpd
      state: installed
      notify:
      - restart httpd
  handlers:
  - name: restart httpd
    service: 
      name: httpd
      state: restarted

